name: NFT Catalog Integration Tests

on: pull_request

jobs:
  tests:
    env:
      CATALOG_TESTNET_PRIVATE_KEY: ${{ secrets.CATALOG_TESTNET_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      # TODO: Move this to proper URL once secure cadence is actually released
      - name: Install FLOW CLI
        run:  sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" -- v0.33.1-sc-m5

      - name: Update PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: npm install

      - name: Run JS Tests
        run: npm test